---
# reference: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests
name: "Enhancement"
description: "I want to suggest an enhancement."
title: "[Enhancement] "
labels: [
  "enhancement"
]
body:
  - type: markdown
    attributes:
      value: |
        Requesting a new feature or enhancement is following some simple rules:

        - **Check**, if the feature is already requested
        - **Describe** what your feature will bring to the community
        - **Explain** the criteria to fulfill the request
        - **Add** more details like mock ups, attachments, lists, screenshots
        - **Follow Up** in the discussion to the feature

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please describe the feature and why it will be useful to the community
      placeholder: Short and explicit description of your feature...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional information"
      description: Please add information like mockups, code snippets, flow diagrams, etc
    validations:
      required: false
