---
name: Reusable workflow for ansible-lint

on:
  workflow_call:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
  
      - name: Run ansible-lint
        uses: ansible/ansible-lint@e7f397ad6dfa20d274afa17cd7bbedd84ed136f5 # v26.9.0
