---
name: Reusable workflow for ansible-lint

on:
  workflow_call:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
  
      - name: Run ansible-lint
        uses: ansible/ansible-lint@e7f397ad6dfa20d274afa17cd7bbedd84ed136f5 # v26.9.0
