---
name: Reusable workflow for ansible-lint

on:
  workflow_call:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
  
      - name: Run ansible-lint
        uses: ansible/ansible-lint@19f673a091111d07688352cd2f19f0460055feba # v26.2.0
