---
name: Codespell - Spellcheck

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches: [main]

jobs:
  codespell:
    uses: "telekom-mms/.github/.github/workflows/codespell.yml@a6f64fa15d004728edacc93d9711c4425f9e5797" # main
