---
name: Codespell - Spellcheck

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches: [main]

jobs:
  codespell:
    uses: "telekom-mms/.github/.github/workflows/codespell.yml@a21264a27236d50165fdfcf6aedacc91135d9418" # main
