---
name: Codespell - Spellcheck

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches: [main]

jobs:
  codespell:
    uses: "telekom-mms/.github/.github/workflows/codespell.yml@e55f61776c6c6a1c082d1d91d5b408c6dbdb75ae" # main
