---
name: Github Repository Settings

on:
  workflow_call:

env:
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up yq
        uses: frenck/action-setup-yq@v1

      - name: get and set repository settings
        run: |
          yq e '.repo' .github/settings.yaml > gh_repo
          cat gh_repo | while read repo_cmd; do echo $repo_cmd | tr -d ':' | awk -v repo=${GITHUB_REPOSITORY} '{printf("gh repo edit %s --%s %s\n", repo, $1, $2)}'; done
