---
name: Github Repository Settings

on:
  workflow_call:
    inputs:
      settings:
        description: 'path/name of the settings file'
        type: string
        required: false
        default: '.github/settings.yaml'
    secrets:
      GH_CLI_TOKEN:
        description: 'PSA Token for gh cli access.'
        required: false

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up yq
        uses: frenck/action-setup-yq@v1

      - name: gh repo edit
        run: |
          # add-topic must be splittet into one command for each topic
          yq '.repo | del(.add-topic)' ${SETTINGS} | tr -d : >  gh_repo
          yq '(.repo.add-topic).[] | sub("(.*)", "add-topic ${0}")' ${SETTINGS} >>  gh_repo
          # get and set settings
          cat gh_repo | while read repo_cmd; do echo $repo_cmd && gh repo edit --$repo_cmd; done
        env:
          SETTINGS: ${{ inputs.settings }}
          GH_TOKEN: ${{ secrets.GH_CLI_TOKEN }}
