---
name: Github Repository Settings

on:
  workflow_call:

env:
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up yq
        uses: frenck/action-setup-yq@v1

      - name: get and set repository settings
        run: |
          yq e '.repo' .github/settings.yaml > gh_repo
          cat gh_repo | tr -d : | while read repo_cmd; do gh repo edit ${GITHUB_REPOSITORY} --$repo_cmd; done
