---
name: GitHub Repository Settings

on:
  workflow_call:
    secrets:
      GH_APP_CREDENTIALS_TOKEN:
        description: 'GitHub Application password'
        required: true
    inputs:
      settings:
        description: 'path/name of the settings file'
        type: string
        required: false
        default: '.github/settings.json'

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup jq
        uses: dcarbone/install-jq-action@91d8da7268538e8a0ae0c8b72af44f1763228455 # v1.0.1

      - name: Obtain a GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo token=${TOKEN} >> $GITHUB_OUTPUT

      - name: Get API
        id: api
        run: |
          echo repos=$(jq -e '.repos| del(.topics)' ${SETTINGS} >/dev/null; echo $?) >> $GITHUB_OUTPUT
          echo collaborators=$(jq -e '.collaborators' ${SETTINGS} >/dev/null; echo $?) >> $GITHUB_OUTPUT
          echo branches=$(jq -e '.branches' ${SETTINGS} >/dev/null; echo $?) >> $GITHUB_OUTPUT
        env:
          SETTINGS: ${{ inputs.settings }}

      # needs administration permission on repository
      - name: Add repository Settings
        if: (steps.api.outputs.repos != 1)
        run: |
          DATA=$(jq '.repos| del(.topics)' ${SETTINGS})
          DATA_TOPICS=$(jq '.repos.topics' ${SETTINGS})

          curl -X PATCH -H 'Accept: application/vnd.github+json' -H "Authorization: Bearer ${GITHUB_TOKEN}" --url "https://api.github.com/repos/${{ github.repository }}" -d "${DATA}"
          curl -X PUT -H 'Accept: application/vnd.github+json' -H "Authorization: Bearer ${GITHUB_TOKEN}" --url "https://api.github.com/repos/${{ github.repository }}/topics" -d "${DATA_TOPICS}"
        env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
          SETTINGS: ${{ inputs.settings }}

      - name: Add repository Collaborators
        if: (steps.api.outputs.collaborators != 1)
        run: |
          DATA=$(jq -e '.collaborators | to_entries | .[] | "\(.key).\(.value)"' ${SETTINGS} | tr -d '"')

          for COLLABORATOR in ${DATA}; do curl -X PUT -H 'Accept: application/vnd.github+json' -H "Authorization: Bearer ${GITHUB_TOKEN}" --url "https://api.github.com/repos/${{ github.repository }}/collaborators/$(echo ${COLLABORATOR} | cut -d '.' -f1)" -d '{"permission":"$(echo ${COLLABORATOR} | cut -d '.' -f2)"}'; done
        env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
          SETTINGS: ${{ inputs.settings }}

      - name: Add repository branches Protection
        if: (steps.api.outputs.branches != 1)
        run: |
          DATA=$(jq -e '.branches | to_entries | .[] | "\(.key).\(.value)"' ${SETTINGS})

          for BRANCH_DATA in ${DATA}; do BRANCH=$(echo ${BRANCH_DATA} | cut -d '.' -f1) && JSON_DATA=$(echo ${BRANCH_DATA//\\} | cut -d '.' -f2) && curl -X PUT -H 'Accept: application/vnd.github+json' -H "Authorization: Bearer ${GITHUB_TOKEN}" --url "https://api.github.com/repos/${{ github.repository }}/branches/${BRANCH:1}/protection" -d "${JSON_DATA:0:-1}"; done
        env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
          SETTINGS: ${{ inputs.settings }}
