---
name: Github Repository Settings

on:
  workflow_call:

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get file changes
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2
        with:
          output: ','
      - uses: mkrakowitzer/actions-ghsettings@v1.3
        if: steps.get_file_changes.outputs.files_modified
        with:
          files: ${{ steps.get_file_changes.outputs.files_modified }}
        env:
          MU_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORG: T-Systems-MMS
      - uses: mkrakowitzer/actions-ghsettings@v1.3
        if: steps.get_file_changes.outputs.files_added
        with:
          files: ${{ steps.get_file_changes.outputs.files_added }}
        env:
          MU_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORG: T-Systems-MMS
