---
name: Github Repository Settings

on:
  workflow_call:

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: mkrakowitzer/actions-ghsettings@v1.3
        with:
          files: .github/settings.yaml
        env:
          MU_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORG: ${{ GITHUB_REPOSITORY }}
