---
name: Settings

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * *'

jobs:
  call-settings:
    uses: telekom-mms/.github/.github/workflows/github_repository.yml@c7c297f53d0f7e2057ac9a7adcb71e6a3ec87a80 # main
    secrets:
      GH_APP_CREDENTIALS_TOKEN: ${{ secrets.GH_APP_CREDENTIALS_TOKEN }}
