---
name: Settings

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * *'

jobs:
  call-settings:
    uses: telekom-mms/.github/.github/workflows/github_repository.yml@62d1de05bc2fdd3bc50699829115b5f8c07feade # main
    secrets:
      GH_APP_CREDENTIALS_TOKEN: ${{ secrets.GH_APP_CREDENTIALS_TOKEN }}
