---
name: Terrascan

on:
  workflow_call:
    inputs:
      iac_type:
        required: true
        type: string
        default: terraform
        description: e.g. helm, k8s, kustomize, terraform - to see all supported types look at https://github.com/tenable/terrascan-action#iac_type
      iac_dir:
        required: false
        type: string
        default: tests
        description: path to directory to scan
      policy_type:
        required: false
        type: string
        default: all
        description: e.g. all, aws, azure, gcp, github, k8s - to see all supported types look at https://github.com/tenable/terrascan-action#policy_type
      non_recursive:
        required: false
        type: boolean
        default: false
        description: do not scan directories and modules recursively


jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Terrascan
        uses: tenable/terrascan-action@3a6e87da8e244513bd77b631e624552643f794c6 # v1
        with:
          iac_type: ${{ inputs.iac_type }}
          iac_dir: ${{ inputs.iac_dir }}
          policy_type: ${{ inputs.policy_type }}
          non_recursive: ${{ inputs.non_recursive }}
          verbose: true
